# Generated by Django 3.2.3 on 2021-09-06 08:08

from django.db import migrations, models
import django.utils.timezone
import django_matplotlib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('t1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ADMIN_REQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_req_type', models.CharField(max_length=200)),
                ('admin_req_tel_num', models.CharField(max_length=200)),
                ('admin_req_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'admin_req',
            },
        ),
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('figure', django_matplotlib.fields.MatplotlibFigureField()),
            ],
        ),
    ]
