# Generated by Django 3.2.3 on 2021-09-06 08:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ADMIN_REQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_req_type', models.CharField(max_length=200)),
                ('admin_req_tel_num', models.CharField(max_length=200)),
                ('admin_req_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'admin_req',
            },
        ),
        migrations.CreateModel(
            name='CUST_PAY_INFO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_pay_info_card_num', models.CharField(max_length=200)),
                ('cust_pay_info_card_exp_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('cust_pay_info_card_pwd', models.CharField(max_length=200)),
                ('cust_pay_info_card_tel_num', models.CharField(max_length=200)),
                ('cust_pay_info_mobile_num', models.CharField(max_length=200)),
                ('cust_pay_info_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'cust_pay_info',
            },
        ),
        migrations.CreateModel(
            name='CUST_SHOP_CELL_LIST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_shop_cell_list_name', models.CharField(max_length=200)),
                ('cust_shop_cell_list_tel_num', models.CharField(max_length=200)),
                ('cust_shop_cell_list_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('cust_shop_cell_list_credit', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'cust_shop_cell_list',
            },
        ),
        migrations.CreateModel(
            name='MBR_LOGIN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mbr_login_id', models.CharField(max_length=200)),
                ('mbr_login_pw', models.CharField(max_length=200)),
                ('mbr_login_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('mbr_login_req', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'mbr_login',
            },
        ),
        migrations.CreateModel(
            name='MBR_SGN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_name', models.CharField(max_length=200)),
                ('sign_gender', models.CharField(max_length=200)),
                ('sign_birth', models.DateTimeField(default=django.utils.timezone.now)),
                ('sign_phone', models.CharField(max_length=200)),
                ('sign_group', models.CharField(max_length=200)),
                ('sign_store_name', models.CharField(max_length=200)),
                ('sign_Address', models.CharField(max_length=200)),
                ('sign_id', models.CharField(max_length=200)),
                ('sign_pw', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'mbr_sgn',
            },
        ),
        migrations.CreateModel(
            name='REG_SHOP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_shop_name', models.CharField(max_length=200)),
                ('reg_shop_tel_num', models.CharField(max_length=200)),
                ('reg_shop_credit', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'reg_shop',
            },
        ),
        migrations.CreateModel(
            name='SHOP_SVC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_svc_name', models.CharField(max_length=200)),
                ('shop_service_tel_num', models.CharField(max_length=200)),
                ('shop_service_addr', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'shop_svc',
            },
        ),
    ]
