# Generated by Django 3.2.3 on 2021-05-27 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
