# Generated by Django 3.2.3 on 2021-05-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0002_delete_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('pwd', models.CharField(max_length=100)),
                ('regdate', models.DateField(auto_now_add=True)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
    ]
